<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FSH.Starter.WebApi.Keyword.Application</RootNamespace>
    <AssemblyName>FSH.Starter.WebApi.Keyword.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\framework\Core\Core.csproj" />
    <ProjectReference Include="..\Keyword.Domain\Keyword.Domain.csproj" />
    <ProjectReference Include="..\Keyword.TextAnalysis\Keyword.TextAnalysis.csproj" />
  </ItemGroup>

</Project>
