<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RootNamespace>FSH.Starter.WebApi.Keyword.TextAnalysis</RootNamespace>
    <AssemblyName>FSH.Starter.WebApi.Keyword.TextAnalysis</AssemblyName>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Lucene.Net" />
    <PackageReference Include="Lucene.Net.Analysis.Common" />
    <PackageReference Include="Lucene.Net.QueryParser" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
