// <auto-generated/>
// using FSH.Starter.Blazor.Modules.Document.Blazor.API;
using System.Security.Claims;
using FSH.Starter.Blazor.Infrastructure.Api;
using FSH.Starter.Blazor.Infrastructure.Auth;
using FSH.Starter.Blazor.Modules.Document.Blazor.Auth;
using FSH.Starter.BlazorShared;
using FSH.Starter.BlazorShared.Components.EntityTable;
using FSH.Starter.BlazorShared.Components;
using FSH.Starter.Shared.Authorization;
using Mapster;
using Microsoft.AspNetCore.Components;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Pages.Storage;

public partial class AccessRules : MobulePageBase
{
    protected override string Path { get; set; }
    [Inject]
    protected IApiClient _client { get; set; } = default!;

    protected EntityServerTableContext<AccessRuleResponse, Guid, AccessRuleVM> Context { get; set; } = default!;

    private EntityTable<AccessRuleResponse, Guid, AccessRuleVM> _table = default!;

    // private List<AccessRuleResponse> _accessRules = new();
    private List<BucketResponse> _buckets = new();
    private ResourceOwnerDto _resourceOwnerDto {  get; set; } = default!;

    public bool IsBucketEnabled { get; set; } = false;
    bool _canViewAccessRules;
    // Advanced Search

    private Guid? _searchAccessRuleId;
    private Guid? SearchAccessRuleId
    {
        get => _searchAccessRuleId;
        set
        {
            _searchAccessRuleId = value;
            _ = _table.ReloadDataAsync();
        }
    }

    private decimal _searchMinimumRate;
    private decimal SearchMinimumRate
    {
        get => _searchMinimumRate;
        set
        {
            _searchMinimumRate = value;
            _ = _table.ReloadDataAsync();
        }
    }

    private decimal _searchMaximumRate = 9999;
    private decimal SearchMaximumRate
    {
        get => _searchMaximumRate;
        set
        {
            _searchMaximumRate = value;
            _ = _table.ReloadDataAsync();
        }
    }

    protected override void OnParametersSet()
    {
        base.OnParametersSet();
        PopulateContext();
        // Context.AddEditModal.ForceRender();
    }


    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        ClaimsPrincipal user = (await AuthState).User;
        // _canViewAccessRules = await AuthService.HasPermissionAsync(user, FshActions.View, FshResources.AccessRules);
        _canViewAccessRules = await AuthService.HasPermissionAsync(user, ModuleActions.View, ModuleResources.AccessRules);

        // await LoadBucketsAsync();

    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        if (firstRender)
        {
            await PopulateBucketValues();
        }
    }
    private void PopulateContext()
    {
        Context = new(
        entityName: "AccessRule",
        entityNamePlural: "AccessRules",
        entityResource: FshResources.AccessRules,
        fields: new()
        {
                new(accessRule => accessRule.Id, "Id", "Id"),
                // new(accessRule => accessRule.StorageAccount.Id, "Storage Account", "StorageAccountId"),
                // new(accessRule => accessRule.StorageAccount.AccountName, "Storage Account", "StorageAccountName"),
                // new(accessRule => accessRule.Bucket.Name, "Bucket Name", "BucketName"),
                // new(accessRule => accessRule.Bucket.Region, "Region", "Region"),
                new(accessRule => accessRule.ResourceOwnerType, "Owner Type", "ResourceOwnerType"),
                new(accessRule => accessRule.ResourceOwnerId, "Resource Owner Id", "ResourceOwnerId"),
                new(accessRule => accessRule.Read, "Read", "Read"),
                new(accessRule => accessRule.Description, "Description", "Description")
        },
        enableAdvancedSearch: false,
        idFunc: accessRule => accessRule.Id!.Value,
        searchFunc: async filter =>
        {
            var accessRuleCommand = filter.Adapt<SearchAccessRulesCommand>();
            var result = await _client.SearchAccessRulesEndpointAsync(accessRuleCommand);
            return result.Adapt<PaginationResponse<AccessRuleResponse>>();
        },
        createFunc: async accessRule =>
        {
            await _client.CreateAccessRuleEndpointAsync(accessRule.Adapt<CreateAccessRuleCommand>());
        },
        updateFunc: async (id, accessRule) =>
        {
            await _client.UpdateAccessRuleEndpointAsync(id, accessRule.Adapt<UpdateAccessRuleCommand>());
        },
        deleteFunc: async id => await _client.DeleteAccessRuleEndpointAsync(id));
    }


    private async Task PopulateBucketValues()
    {
        if (_buckets.Count == 0)
        {
            var result = await _client.SearchBucketsEndpointAsync(new SearchBucketsRequest() { OrderBy = [], PageNumber = 1, PageSize = 10 });
            _buckets = result.Items.ToList();
        }
    }

    private void OnBucketIdChanged(AccessRuleVM? context, Guid? bucketId)
    {
        if (context != null)
            context.BucketId = bucketId ?? Guid.Empty;
    }
    public class AccessRuleVM : UpdateAccessRuleCommand { }

    private void OnResourceOwnerChanged(AccessRuleVM context, ResourceOwnerDto dto)
    {
        _resourceOwnerDto = dto;
        context.ResourceOwnerType = dto.ResourceOwnerType;
        context.ResourceOwnerId = dto.ResourceOwnerId;
        StateHasChanged();
    }

    private void OnEnabledStateToggled(ref AccessRuleVM contextModel, bool newValue)
    {
        // 1. Force state modification direct into the active form context instance
        contextModel.IsEnabled = newValue;

        // 2. Cascade down to sub-properties if disabled
        if (!newValue)
        {
            contextModel.Read = false;
            contextModel.Write = false;
            contextModel.Execute = false;
        }
        StateHasChanged();
        // 3. FORCE FULLSTACKHERO'S MODAL WRAPPER TO FORCE AN INTERNAL RERENDER PASS
        // This targets the underlying MudDialog state container instead of the base page background
        Context.AddEditModal?.ForceRender();
    }
}
