// <auto-generated/>
// using FSH.Starter.Blazor.Modules.Document.Blazor.API;
using FSH.Starter.Blazor.Modules.Document.Blazor.Auth;
using FSH.Starter.BlazorShared;
using FSH.Starter.Blazor.Infrastructure.Api;
using FSH.Starter.BlazorShared.Components.EntityTable;
using FSH.Starter.Shared.Authorization;
using Mapster;
using Microsoft.AspNetCore.Components;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Pages.Storage;

public partial class Accounts : MobulePageBase
{
    protected override string Path { get; set; }
    [Inject]
    protected IApiClient _client { get; set; } = default!;

    protected EntityServerTableContext<StorageAccountResponse, Guid, StorageAccountVM> Context { get; set; } = default!;

    private EntityTable<StorageAccountResponse, Guid, StorageAccountVM> _table = default!;

    private List<StorageAccountResponse> _storageAccounts = new();


    // Advanced Search

    private Guid? _searchStorageAccountId;
    private Guid? SearchStorageAccountId
    {
        get => _searchStorageAccountId;
        set
        {
            _searchStorageAccountId = value;
            _ = _table.ReloadDataAsync();
        }
    }

    private decimal _searchMinimumRate;
    private decimal SearchMinimumRate
    {
        get => _searchMinimumRate;
        set
        {
            _searchMinimumRate = value;
            _ = _table.ReloadDataAsync();
        }
    }

    private decimal _searchMaximumRate = 9999;
    private decimal SearchMaximumRate
    {
        get => _searchMaximumRate;
        set
        {
            _searchMaximumRate = value;
            _ = _table.ReloadDataAsync();
        }
    }

    protected override void OnParametersSet()
    {
        base.OnParametersSet();
        PopulateContext();
        // Context.AddEditModal.ForceRender();
    }

    protected override void OnInitialized()
    {
        base.OnInitialized();
        // Context.AddEditModal.ForceRender();

    }
    protected override async Task OnInitializedAsync()
    {
        OnInitialized();
        await base.OnInitializedAsync();

    }

    private void PopulateContext()
    {
        Context = new(
       entityName: "StorageAccount",
       entityNamePlural: "StorageAccounts",
       entityResource: FshResources.StorageAccounts,
       fields: new()
       {
                new(storageAccount => storageAccount.Id, "Id", "Id"),
                new(storageAccount => storageAccount.AccountName, "Name", "AccountName"),
                new(storageAccount => storageAccount.AccessKey, "Key", "AccessKey"),
                // new(storageAccount => storageAccount.SecretKey, "Secret", "SecretKey"),
                new(storageAccount => storageAccount.Description, "Description", "Description")
       },
       enableAdvancedSearch: true,
       idFunc: storageAccount => storageAccount.Id!.Value,
       searchFunc: async filter =>
       {
           var storageAccountFilter = filter.Adapt<SearchStorageAccountsCommand>();
           var result = await _client.SearchStorageAccountsEndpointAsync(storageAccountFilter);
           return result.Adapt<PaginationResponse<StorageAccountResponse>>();
       },
       createFunc: async storageAccount =>
       {
           await _client.CreateStorageAccountEndpointAsync(storageAccount.Adapt<CreateStorageAccountCommand>());
       },
       updateFunc: async (id, storageAccount) =>
       {
           await _client.UpdateStorageAccountEndpointAsync(id, storageAccount.Adapt<UpdateStorageAccountCommand>());
       },
       deleteFunc: async id => await _client.DeleteStorageAccountEndpointAsync(id),
       hasExtraActionsFunc: () => true,
       exportAction: string.Empty);
    }

    private void ViewProfile(in Guid? userId) =>
       Navigation.NavigateTo($"/identity/users/{userId}/profile");

    private void ManageRoles(in Guid? userId) =>
        Navigation.NavigateTo($"/identity/users/{userId}/roles");
    private void ViewAuditTrails(in Guid? userId) =>
        Navigation.NavigateTo($"/identity/users/{userId}/audit-trail");

    public class StorageAccountVM : UpdateStorageAccountCommand
    {
    }
}
