// <auto-generated/>
// using FSH.Starter.Blazor.Modules.Document.Blazor.API;
using System;
using System.Security.Claims;
using FSH.Starter.Blazor.Infrastructure.Api;
using FSH.Starter.Blazor.Infrastructure.Auth;
using FSH.Starter.Blazor.Modules.Document.Blazor.Auth;
using FSH.Starter.BlazorShared;
using FSH.Starter.BlazorShared.Components.EntityTable;
using FSH.Starter.Shared.Authorization;
using Mapster;
using Microsoft.AspNetCore.Components;
using Microsoft.Extensions.Logging;
using Nextended.Core.Extensions;
using static FSH.Starter.Blazor.Modules.Document.Blazor.Pages.Storage.Accounts;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Pages.Storage;

public partial class Buckets : MobulePageBase
{
    protected override string Path { get; set; }
    [Inject]
    protected IApiClient _client { get; set; } = default!;

    [Inject]
    protected ILogger<Buckets> _logger { get; set; } = default!;

    protected EntityServerTableContext<BucketResponse, Guid, BucketVM> Context { get; set; } = default!;

    private EntityTable<BucketResponse, Guid, BucketVM> _table = default!;

    // private List<AccessRuleResponse> _accessRules = new();
    private List<StorageAccountResponse> _storageAccounts = new();
    private List<RegionResponse> _regions = new();

    private bool _loadingRegions;
    private Guid _currentStorageAccountId;
    bool _canViewBuckets;
    // Advanced Search

    private Guid? _searchBucketId;
    private Guid? SearchBucketId
    {
        get => _searchBucketId;
        set
        {
            _searchBucketId = value;
            _ = _table.ReloadDataAsync();
        }
    }

    private Guid? _storageAccountId;
    protected override void OnParametersSet()
    {
        base.OnParametersSetAsync();


        // Context.AddEditModal.ForceRender();

    }


    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        ClaimsPrincipal user = (await AuthState).User;
        // _canViewAccessRules = await AuthService.HasPermissionAsync(user, FshActions.View, FshResources.AccessRules);
        _canViewBuckets = await AuthService.HasPermissionAsync(user, ModuleActions.View, ModuleResources.Buckets);

        PopulateContext();
        await LoadStorageAccountsAsync();
    }

    private void PopulateContext()
    {
        Context = new(
        entityName: "Bucket",
        entityNamePlural: "Buckets",
        entityResource: FshResources.Buckets,
        fields: new()
        {
                new(bucket => bucket.Id, "Id", "Id"),
                new(bucket => bucket.StorageAccount.AccountName, "Storage Account", "StorageAccount"),
                new(bucket => bucket.ResourceName, "ResourceName", "ResourceName"),
                new(bucket => bucket.Name, "Name", "Name"),
                new(bucket => bucket.Region, "Region", "Region"),
                new(bucket => bucket.Description, "Description", "Description")
        },
        enableAdvancedSearch: true,
        idFunc: bucket => bucket.Id!.Value,
        searchFunc: async filter =>
        {
            var bucketCommand = filter.Adapt<SearchBucketsRequest>();
            var result = await _client.SearchBucketsEndpointAsync(bucketCommand);
            return result.Adapt<PaginationResponse<BucketResponse>>();
        },
        createFunc: async bucket =>
        {
            await _client.CreateBucketEndpointAsync(bucket.Adapt<CreateBucketCommand>());
        },
        updateFunc: async (id, bucket) =>
        {
            await _client.UpdateBucketEndpointAsync(id, bucket.Adapt<UpdateBucketCommand>());
        },
        deleteFunc: async id => await _client.DeleteBucketEndpointAsync(id));
    }


    private async Task LoadStorageAccountsAsync()
    {
        if (_storageAccounts.Count == 0)
        {

            var response = await _client.SearchStorageAccountsEndpointAsync(new SearchStorageAccountsCommand() { });
            if (response?.Items != null)
            {
                _storageAccounts = response.Items.ToList();
            }
        }
    }

    private async Task LoadRegionsAsync(Guid storageAccountId)
    {
        _logger.LogInformation($"Start Getting Regions from service");

        var response = await _client.ListRegionsEndpointAsync(new ListRegionsRequest() { StorageAccountId = storageAccountId });
        if (response?.Items != null)
        {
            _regions = response.Items.ToList();
            _logger.LogInformation($"Regions loaded Count:{_regions.Count}");
            StateHasChanged();
        }
    }

    private async Task<IEnumerable<string>> SearchRegions(string value, CancellationToken token)
    {
        // In real life use an asynchronous function for fetching data from an api.
        // await Task.Delay(1000, token);
        _loadingRegions = true;
        // if text is null or empty, show complete list
        var filter = new Filter() { Field = "systemName", Operator = "Contains", Value = value };
        if(_currentStorageAccountId == Guid.Empty)
        {
            _logger.LogWarning($"StorageAccountId is null or empty, cannot search regions");
            return new List<string>();
        }

        if (string.IsNullOrEmpty(value))
           return (await _client.ListRegionsEndpointAsync(new ListRegionsRequest() { StorageAccountId = _currentStorageAccountId })).Items.Select(x => x.SystemName);   
        // return _regions.Where(x => x.DisplayName.Contains(value, StringComparison.InvariantCultureIgnoreCase)).Select(x => x.SystemName);
        return (await _client.ListRegionsEndpointAsync(new ListRegionsRequest { StorageAccountId = _currentStorageAccountId, Keyword = value })).Items.Select(x => x.SystemName);
    }
    private async Task StorageAccountValueChanged(Guid? newValue)
    {
        _currentStorageAccountId = newValue ?? Guid.Empty;
        // Context.AddEditModal.RequestModel.Name = "AAALLLLLSSSSBBBB";
        // Guid? newValue = Context.AddEditModal.RequestModel.StorageAccountId;
        _logger.LogInformation($"StorageAccountId changed to {newValue}");
        if (newValue != null && newValue != Guid.Empty)
        {
            _logger.LogInformation($"Start Getting Regions for SA-ID:{newValue}");

            await LoadRegionsAsync((Guid)newValue);
            // _ = _table.ReloadDataAsync();
            StateHasChanged();
        }
    }

    public class BucketVM : UpdateBucketCommand
    {
        public string Region { get; set; }
    }
}
