// <auto-generated/>
// using FSH.Starter.Blazor.Modules.Document.Blazor.API;
using System.Security.Claims;
using FSH.Starter.Blazor.Infrastructure.Api;
using FSH.Starter.Blazor.Infrastructure.Auth;
using FSH.Starter.Blazor.Modules.Document.Blazor.Auth;
using FSH.Starter.BlazorShared;
using FSH.Starter.BlazorShared.Components.EntityTable;
using FSH.Starter.Shared.Authorization;
using Mapster;
using Microsoft.AspNetCore.Components;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Pages.Storage;

public partial class Buckets : MobulePageBase
{
    protected override string Path { get; set; }
    [Inject]
    protected IApiClient _client { get; set; } = default!;

    protected EntityServerTableContext<BucketResponse, Guid, BucketVM> Context { get; set; } = default!;

    private EntityTable<BucketResponse, Guid, BucketVM> _table = default!;

    // private List<AccessRuleResponse> _accessRules = new();
    private List<BucketResponse> _buckets = new();

    bool _canViewBuckets;
    // Advanced Search

    private Guid? _searchBucketId;
    private Guid? SearchBucketId
    {
        get => _searchBucketId;
        set
        {
            _searchBucketId = value;
            _ = _table.ReloadDataAsync();
        }
    }

    protected override void OnParametersSet()
    {
        base.OnParametersSet();
        PopulateContext();
        // Context.AddEditModal.ForceRender();
    }


    protected override async Task OnInitializedAsync()
    {
        
        ClaimsPrincipal user = (await AuthState).User;
        // _canViewAccessRules = await AuthService.HasPermissionAsync(user, FshActions.View, FshResources.AccessRules);
        _canViewBuckets = await AuthService.HasPermissionAsync(user, ModuleActions.View, ModuleResources.Buckets);
        // await LoadBucketsAsync(); 
        await base.OnInitializedAsync();

    }

    private void PopulateContext()
    {
       Context = new(
       entityName: "Bucket",
       entityNamePlural: "Buckets",
       entityResource: FshResources.Buckets,
       fields: new()
       {
                new(bucket => bucket.Id, "Id", "Id"),
                new(bucket => bucket.StorageAccount.AccountName, "Storage Account", "StorageAccount"),
                new(bucket => bucket.ResourceName, "ResourceName", "ResourceName"),
                new(bucket => bucket.Name, "Name", "Name"),
                new(bucket => bucket.Region, "Region", "Region"),
                new(bucket => bucket.Description, "Description", "Description")
       },
       enableAdvancedSearch: true,
       idFunc: bucket => bucket.Id!.Value,
       searchFunc: async filter =>
       {
           var bucketCommand = filter.Adapt<SearchBucketsRequest>();
           var result = await _client.SearchBucketsEndpointAsync(bucketCommand);
           return result.Adapt<PaginationResponse<BucketResponse>>();
       },
       createFunc: async bucket =>
       {
           await _client.CreateBucketEndpointAsync(bucket.Adapt<CreateBucketCommand>());
       },
       updateFunc: async (id, bucket) =>
       {
           await _client.UpdateBucketEndpointAsync(id, bucket.Adapt<UpdateBucketCommand>());
       },
       deleteFunc: async id => await _client.DeleteBucketEndpointAsync(id));
    }


    private async Task LoadBucketsAsync()
    {
        if (_buckets.Count == 0)
        {
            
            var response = await _client.SearchBucketsEndpointAsync(new SearchBucketsRequest() { });
            if (response?.Items != null)
            {
                _buckets = response.Items.ToList();
            }
        }
    }

    public class BucketVM : UpdateBucketCommand
    {
    }
}
