<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FSH.Starter.Blazor.Modules.MudBlazorBlocks.Blazor</RootNamespace>
    <AssemblyName>FSH.Starter.Blazor.Modules.MudBlazorBlocks.Blazor</AssemblyName>
    
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <BlazorWebAssemblySupportedCultures>en;ar</BlazorWebAssemblySupportedCultures>
    <BlazorWebAssemblyDefaultCulture>ar</BlazorWebAssemblyDefaultCulture>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Abstraction\TreeNode\TreeNode.jpg" />
    <None Remove="Abstraction\TreeNode\TreeNodeFilterBuilder.jpg" />
    <None Remove="Abstraction\TreeNode\TreeNodeUtility.jpg" />
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elsa.Workflows.Core" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="MudBlazor.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Blazor.Shared\BlazorShared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\MudBlazorBlocksResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MudBlazorBlocksResources.resx</DependentUpon>
    </Compile>
    <None Include="Abstraction\BlockNode\Inputs\InputComponentBase2.csbak" />
    <None Include="Abstraction\BlockNode\Inputs\InputComponentBase.csbak" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\MudBlazorBlocksResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MudBlazorBlocksResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstraction\BlockNode\Studio\" />
    <Folder Include="Components\Blocks\Dialogs\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Pages\MudBlazorBlocks\BlockNodeEditor.razorbak">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\Blocks\EditForm\BlockNodeValidationManager.razorBak">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

</Project>
