<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FSH.Starter.WebApi.Keyword.Domain</RootNamespace>
    <AssemblyName>FSH.Starter.WebApi.Keyword.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Events\" />
    <Folder Include="Exceptions\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\framework\Core\Core.csproj" />
  </ItemGroup>

</Project>
