// <auto-generated/>
using Microsoft.AspNetCore.Components;
using MudBlazor;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Dialogs;
public partial class RenameDialog
{
    [CascadingParameter] IMudDialogInstance MudDialog { get; set; } = default!;
    [Parameter] public string CurrentName { get; set; } = string.Empty;
    string NewName = string.Empty;

    void Cancel() => MudDialog.Cancel();

    void Save() => MudDialog.Close(DialogResult.Ok(NewName.Trim()));
}
