// <auto-generated/>

using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Dialogs;
using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Models;
using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.JSInterop;
using MudBlazor;
using Shared.Enums;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Components;

public partial class FileExplorerComponent
{
    //[Inject] ISnackbar Snackbar { get; set; } = default!;
    [Inject] IFileExplorerStateService StateService { get; set; } = default!;

    [Parameter] public bool AllowMultipleSelection { get; set; }

    private List<FolderModel> Folders = new();
    private FolderModel CurrentFolder {get; set;}//=> _currentFolder ??= Folders.First();
                                                 // private FolderModel? _currentFolder;
    private bool _open = true;

    private void ToggleFileBrowserTree(bool opened)
    {
        _open = opened;
    }
    protected override void OnInitialized()
    {
        StateService.OnFileExplorerClearSelection += ClearSelection;

        var root = new FolderModel($"Root", new[] {
                    new FileModel(Guid.NewGuid(), $"Report.pdf", 245_760, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-2)),
                    new FileModel(Guid.NewGuid(), $"door.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"iceland.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"tractor-very-long-file-name-wraptext.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"castle.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"pilars.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"sweden.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"document_01.docx", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"document_02.doc", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"document_03.xlsx", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"document_04.xls", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"document_05.mdb", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"document_05.accdb", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), $"Notes.txt", 1024, DateTime.Now.AddDays(-2), DateTime.Now.AddHours(-5))
        },
           new[] {
                new FolderModel("Projects", new[] {
                            new FileModel(Guid.NewGuid(), "project1.png", 512_000, DateTime.Now.AddDays(-15), DateTime.Now.AddDays(-10)),
                            new FileModel(Guid.NewGuid(), "project2.png", 768_000, DateTime.Now.AddDays(-12), DateTime.Now.AddDays(-8))
                        } ){ Path = $"{Constants._content}/img/projects", AllowedExtensions="mpeg" },
                new FolderModel("Vacations", new[]{
                            new FileModel(Guid.NewGuid(), "beach.png", 1_024_000, DateTime.Now.AddDays(-30), DateTime.Now.AddDays(-25)),
                            new FileModel(Guid.NewGuid(), "mountains.png", 1_536_000, DateTime.Now.AddDays(-28), DateTime.Now.AddDays(-20))
                        }){Path = $"{Constants._content}/img/vacations" , AllowedExtensions="jpg" },
                new FolderModel("Docs files", new[]{
                            new FileModel(Guid.NewGuid(), "beach.png", 1_024_000, DateTime.Now.AddDays(-30), DateTime.Now.AddDays(-25)),
                            new FileModel(Guid.NewGuid(), "mountains.png", 1_536_000, DateTime.Now.AddDays(-28), DateTime.Now.AddDays(-20))
                        }){Path = $"{Constants._content}/img/vacations" , AllowedExtensions="jpg,docx" },
                new FolderModel("Music files", new[]{
                            new FileModel(Guid.NewGuid(), "beach.png", 1_024_000, DateTime.Now.AddDays(-30), DateTime.Now.AddDays(-25)),
                            new FileModel(Guid.NewGuid(), "mountains.png", 1_536_000, DateTime.Now.AddDays(-28), DateTime.Now.AddDays(-20))
                        }){Path = $"{Constants._content}/img/vacations" , AllowedExtensions="mp3" }
           }
        
        ) { Path = $"{Constants._content}/img/" };

        Folders.Add(root);

        var shared = new FolderModel("Shared", new[]
        {
            new FileModel(Guid.NewGuid(), "Meeting.mp4", 50_000_000, DateTime.Now.AddDays(-20), DateTime.Now.AddDays(-20))
        }){ Path = $"{Constants._content}/" };

        Folders.Add(shared);
        var archive = new FolderModel("Archive"){ Path = $"{Constants._content}/archive" };

        Folders.Add(archive);


        // _currentFolder = Folders.First();
        CurrentFolder = Folders.First();
    }

    void OnFolderSelected(FolderModel folder)
    {
        // _currentFolder = folder;
        CurrentFolder = folder;
        StateHasChanged();
    }
    

    void ClearSelection()
    {
        if (!AllowMultipleSelection)
        {
            foreach (var folder in CurrentFolder.Folders)
            {
                folder.UnSelect();
            }
            foreach (var file in CurrentFolder.Files)
            {
                file.UnSelect();
            }
        }
    }
    // Optional stronger upload handler using InputFile:
    async Task OnInputFileChange(InputFileChangeEventArgs e)
    {
        foreach (var browserFile in e.GetMultipleFiles())
        {
            var model = new FileModel(Guid.NewGuid(), browserFile.Name, browserFile.Size, DateTime.Now, DateTime.Now);
            CurrentFolder.AddFile(model);
        }
        Toast.Add($"Uploaded {e.GetMultipleFiles().Count} file(s).", Severity.Success);
    }

    
async Task OnFolderUpdated(ICollection<FolderModel> updatedFolders)
    {
        Folders = updatedFolders.ToList();
        // Ensure current folder reference is updated
        // _currentFolder = Folders.FirstOrDefault(f => f.Name == CurrentFolder.Name) ?? Folders.First();
        await InvokeAsync(StateHasChanged);
    }   

    public void Dispose() {
        StateService.OnFileExplorerClearSelection -= ClearSelection;
    }
}


//// Seed sample data - replace with real backend loading
//Folders = new List<FolderModel>
//{
//    new FolderModel($"Root")
//    {
//        Path = $"{Constants._content}/img/",
//        Folders =
//        {
//            new FolderModel("Projects")
//            {
//                Path = $"{Constants._content}/img/projects",
//                Files.
//                {
//                    new FileModel(Guid.NewGuid(), "project1.png", 512_000, DateTime.Now.AddDays(-15), DateTime.Now.AddDays(-10)),
//                    new FileModel(Guid.NewGuid(), "project2.png", 768_000, DateTime.Now.AddDays(-12), DateTime.Now.AddDays(-8))
//                }
//            },
//            new FolderModel("Vacations")
//            {
//                Path = $"{Constants._content}/img/vacations",
//                Files =
//                {
//                    new FileModel(Guid.NewGuid(), "beach.png", 1_024_000, DateTime.Now.AddDays(-30), DateTime.Now.AddDays(-25)),
//                    new FileModel(Guid.NewGuid(), "mountains.png", 1_536_000, DateTime.Now.AddDays(-28), DateTime.Now.AddDays(-20))
//                }
//            }
//        },
//        Files =
//        {
//            new FileModel(Guid.NewGuid(), $"{Constants._content}/img/Report.pdf", 245_760, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-2)),
//            new FileModel(Guid.NewGuid(), $"{Constants._content}/img/door.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
//            new FileModel(Guid.NewGuid(), $"{Constants._content}/img/iceland.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
//            new FileModel(Guid.NewGuid(), $"{Constants._content}/img/tractor.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
//            new FileModel(Guid.NewGuid(), $"{Constants._content}/img/castle.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
//            new FileModel(Guid.NewGuid(), $"{Constants._content}/img/pilars.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
//            new FileModel(Guid.NewGuid(), $"{Constants._content}/img/sweden.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
//            new FileModel(Guid.NewGuid(), $"{Constants._content}/img/Notes.txt", 1024, DateTime.Now.AddDays(-2), DateTime.Now.AddHours(-5))
//        }
//    },
//    new FolderModel("Shared")
//    {
//        Path = $"{Constants._content}/",
//        Files =
//        {
//            new FileModel(Guid.NewGuid(), "Meeting.mp4", 50_000_000, DateTime.Now.AddDays(-20), DateTime.Now.AddDays(-20))
//        }
//    },
//    new FolderModel("Archive"){
//        Path = $"{Constants._content}/archive",
//        Files = { }
//    }
//};
