// <auto-generated/>

using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Models;
using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Dialogs;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.JSInterop;
using MudBlazor;
using Shared.Enums;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Components;

public partial class FileExplorerComponent
{
    //[Inject] ISnackbar Snackbar { get; set; } = default!;

    


    private List<FolderModel> Folders = new();
    private FolderModel CurrentFolder {get; set;}//=> _currentFolder ??= Folders.First();
    // private FolderModel? _currentFolder;
    
    protected override void OnInitialized()
    {
        // Seed sample data - replace with real backend loading
        Folders = new List<FolderModel>
        {
            new FolderModel("Root")
            {
                Files =
                {
                    new FileModel(Guid.NewGuid(), "Report.pdf", 245_760, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-2)),
                    new FileModel(Guid.NewGuid(), "Photo.jpg", 1_048_576, DateTime.Now.AddDays(-2), DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), "Notes.txt", 1024, DateTime.Now.AddDays(-2), DateTime.Now.AddHours(-5))
                }
            },
            new FolderModel("Shared")
            {
                Files =
                {
                    new FileModel(Guid.NewGuid(), "Meeting.mp4", 50_000_000, DateTime.Now.AddDays(-20), DateTime.Now.AddDays(-20))
                }
            },
            new FolderModel("Archive")
        };

        // _currentFolder = Folders.First();
        CurrentFolder = Folders.First();
    }

    void OnFolderSelected(FolderModel folder)
    {
        // _currentFolder = folder;
        CurrentFolder = folder;
        StateHasChanged();
    }
    

  
    // Optional stronger upload handler using InputFile:
    async Task OnInputFileChange(InputFileChangeEventArgs e)
    {
        foreach (var browserFile in e.GetMultipleFiles())
        {
            var model = new FileModel(Guid.NewGuid(), browserFile.Name, browserFile.Size, DateTime.Now, DateTime.Now);
            CurrentFolder.Files.Add(model);
        }
        Toast.Add($"Uploaded {e.GetMultipleFiles().Count} file(s).", Severity.Success);
    }

    
async Task OnFolderUpdated(ICollection<FolderModel> updatedFolders)
    {
        Folders = updatedFolders.ToList();
        // Ensure current folder reference is updated
        // _currentFolder = Folders.FirstOrDefault(f => f.Name == CurrentFolder.Name) ?? Folders.First();
        await InvokeAsync(StateHasChanged);
    }   

}
