// <auto-generated/>
using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Dialogs;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.JSInterop;
using MudBlazor;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer;
public partial class FileExplorerDialog
{
    // Inject MudBlazor services
    // [Inject] IDialogService DialogService { get; set; } = default!;

    [CascadingParameter] IMudDialogInstance MudDialog { get; set; } = default!;
    [Inject] ISnackbar Snackbar { get; set; } = default!;

    // UI refs & state
    private ElementReference fileInput;
    private bool ShowNewFolderInput;
    private string NewFolderName = string.Empty;
    private string Search = string.Empty;
    record FileModel(Guid Id, string Name, long Size, DateTime Modified);
    record FolderModel(string Name)
    {
        public List<FileModel> Files { get; init; } = new();
    }

    private List<FolderModel> Folders = new();
    private FolderModel CurrentFolder => _currentFolder ??= Folders.First();
    private FolderModel? _currentFolder;
    private string Breadcrumb => $"/{CurrentFolder.Name}";

    protected override void OnInitialized()
    {
        // Seed sample data - replace with real backend loading
        Folders = new List<FolderModel>
        {
            new FolderModel("Root")
            {
                Files =
                {
                    new FileModel(Guid.NewGuid(), "Report.pdf", 245_760, DateTime.Now.AddDays(-2)),
                    new FileModel(Guid.NewGuid(), "Photo.jpg", 1_048_576, DateTime.Now.AddDays(-10)),
                    new FileModel(Guid.NewGuid(), "Notes.txt", 1024, DateTime.Now.AddHours(-5))
                }
            },
            new FolderModel("Shared")
            {
                Files =
                {
                    new FileModel(Guid.NewGuid(), "Meeting.mp4", 50_000_000, DateTime.Now.AddDays(-20))
                }
            },
            new FolderModel("Archive")
        };

        _currentFolder = Folders.First();
    }

    void ChangeFolder(FolderModel f)
    {
        _currentFolder = f;
    }

    void ToggleNewFolder()
    {
        ShowNewFolderInput = !ShowNewFolderInput;
        NewFolderName = string.Empty;
    }

    void CreateFolder()
    {
        var name = (NewFolderName ?? string.Empty).Trim();
        if (string.IsNullOrWhiteSpace(name))
        {
            Snackbar.Add("Enter a valid folder name.", Severity.Warning);
            return;
        }

        if (Folders.Any(x => string.Equals(x.Name, name, StringComparison.OrdinalIgnoreCase)))
        {
            Snackbar.Add("A folder with that name already exists.", Severity.Warning);
            return;
        }

        var folder = new FolderModel(name);
        Folders.Add(folder);
        _currentFolder = folder;
        ShowNewFolderInput = false;
        Snackbar.Add($"Folder '{name}' created.", Severity.Success);
    }

    async Task TriggerFileInput()
    {
        // focus click the hidden input to show native file picker
        await fileInput.FocusAsync();
        await JSRuntime.InvokeVoidAsync("eval", "document.querySelectorAll('input[type=file]')[0].click()");
    }

    [Inject] IJSRuntime JSRuntime { get; set; } = default!;

    async Task HandleUpload(ChangeEventArgs e)
    {
        // Using ChangeEventArgs because ElementReference click -> native input change
        // For richer usage use InputFile component with InputFileChangeEventArgs
        // We'll try to cast: in Blazor wasm you'll likely use InputFile; this minimal handler simulates
        // NOTE: If you prefer InputFile, replace markup to <InputFile OnChange="OnInputFileChange" /> and implement OnInputFileChange(InputFileChangeEventArgs)
        Snackbar.Add("Files selected (simulate upload). Implement backend upload in HandleUpload.", Severity.Info);
    }

    // Optional stronger upload handler using InputFile:
    async Task OnInputFileChange(InputFileChangeEventArgs e)
    {
        foreach (var browserFile in e.GetMultipleFiles())
        {
            var model = new FileModel(Guid.NewGuid(), browserFile.Name, browserFile.Size, DateTime.Now);
            CurrentFolder.Files.Add(model);
        }
        Snackbar.Add($"Uploaded {e.GetMultipleFiles().Count} file(s).", Severity.Success);
    }

    void Refresh()
    {
        // Replace with re-fetch from server
        Snackbar.Add("Refreshed.", Severity.Info);
        StateHasChanged();
    }

    string FormatSize(long size)
    {
        if (size >= 1 << 30) return $"{size / (1 << 30)} GB";
        if (size >= 1 << 20) return $"{size / (1 << 20)} MB";
        if (size >= 1 << 10) return $"{size / (1 << 10)} KB";
        return $"{size} B";
    }

    string GetFileIcon(string fileName)
    {
        var ext = Path.GetExtension(fileName).ToLowerInvariant();
        return ext switch
        {
            ".jpg" or ".jpeg" or ".png" or ".gif" => Icons.Material.Filled.Image,
            ".pdf" => Icons.Material.Filled.PictureAsPdf,
            ".mp4" or ".mov" => Icons.Material.Filled.Movie,
            ".txt" or ".md" => Icons.Material.Filled.Description,
            ".doc" or ".docx" => Icons.Material.Filled.Article,
            _ => Icons.Material.Filled.InsertDriveFile
        };
    }

    async Task DownloadFile(FileModel f)
    {
        // Replace with actual file download logic (link to blob or invoking API).
        Snackbar.Add($"Simulated download: {f.Name}", Severity.Info);
    }

    async Task DeleteFile(FileModel f)
    {
        bool? result = await DialogService.ShowMessageBox(
            "Confirm Delete",
            $"Delete file '{f.Name}'?",
            yesText: "Delete",
            noText: "Cancel",
            options: new DialogOptions { CloseButton = true }
        );

        if (result == true)
        {
            CurrentFolder.Files.Remove(f);
            Snackbar.Add($"Deleted {f.Name}", Severity.Success);
            StateHasChanged();
        }
    }

    async Task RenameFilePrompt(FileModel f)
    {
        var parameters = new DialogParameters { ["CurrentName"] = f.Name };
        var dialog = DialogService.Show<RenameDialog>("Rename file", parameters);
        var res = await dialog.Result;
        if (!res.Canceled && res.Data is string newName && !string.IsNullOrWhiteSpace(newName))
        {
            var idx = CurrentFolder.Files.FindIndex(x => x.Id == f.Id);
            if (idx >= 0)
            {
                CurrentFolder.Files[idx] = f with { Name = newName };
                Snackbar.Add($"Renamed to {newName}", Severity.Success);
            }
        }
    }


    private void Submit() => MudDialog.Close(DialogResult.Ok(true));

    private void Cancel() => MudDialog.Cancel();
}
