// <auto-generated/>
using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Dialogs;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.JSInterop;
using MudBlazor;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer;
public partial class FileExplorerDialog
{
    // Inject MudBlazor services
    // [Inject] IDialogService DialogService { get; set; } = default!;

    [CascadingParameter] IMudDialogInstance MudDialog { get; set; } = default!;
    


    private void Submit() => MudDialog.Close(DialogResult.Ok(true));

    private void Cancel() => MudDialog.Cancel();
}
