<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>FSH.Starter.WebApi.PluginsManager.Infrastructure</RootNamespace>
    <AssemblyName>FSH.Starter.WebApi.PluginsManager.Infrastructure</AssemblyName>
  </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\..\framework\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\PluginsManager.Application\PluginsManager.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Persistence\Configurations\" />
      <Folder Include="Services\" />
    </ItemGroup>

</Project>
