// <auto-generated/>
using System.Diagnostics.CodeAnalysis;
using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer;
using FSH.Starter.BlazorShared;
using MudBlazor;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Pages.Document;
// [Microsoft.AspNetCore.Components.Route("/documents/list")]
public partial class List : MobulePageBase
{
    protected override string Path { get; set; }

    private Task OpenDialogAsync()
    {
        var options = new DialogOptions { CloseOnEscapeKey = true, MaxWidth = MaxWidth.ExtraExtraLarge, BackdropClick = false };

        return DialogService.ShowAsync<FileExplorerDialog>("File Explorer Dialog", options);
    }
}
