// <auto-generated/>
using System.Diagnostics.CodeAnalysis;
using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer;
using FSH.Starter.BlazorShared;
using Microsoft.AspNetCore.Components;
using MudBlazor;

namespace FSH.Starter.Blazor.Modules.Document.Blazor.Pages.Document;
// [Microsoft.AspNetCore.Components.Route("/documents/list")]
public partial class List : MobulePageBase
{
    [CascadingParameter(Name = "PageTitle")] public string PageTitle { get; set; }

    protected override string Path { get; set; }

    private MudSplitPanel _splitPanel;
    private bool _horizontal;
    private bool _resetOnDoubleClick = true;
    private bool _rounded = true;
    private bool _elevation = true;
    private bool _transparent;


    protected override void OnInitialized()
    {
        base.OnInitialized();
        PageTitle = "Document List";
    }
    private Task OpenDialogAsync()
    {
        var options = new DialogOptions { CloseOnEscapeKey = true, MaxWidth = MaxWidth.ExtraExtraLarge, BackdropClick = false };

        return DialogService.ShowAsync<FileExplorerDialog>("File Explorer Dialog", options);
    }
}
