// <auto-generated/>
using System.Diagnostics.CodeAnalysis;
using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer;
using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Helpers;
using FSH.Starter.Blazor.Modules.Document.Blazor.Components.FileExplorer.Models;
using FSH.Starter.BlazorShared;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using MudBlazor;
namespace FSH.Starter.Blazor.Modules.Document.Blazor.Pages.Document;
// [Microsoft.AspNetCore.Components.Route("/documents/list")]
public partial class List : MobulePageBase
{
    [CascadingParameter(Name = "PageTitle")] public string PageTitle { get; set; }

    /// <summary>
    /// The MudFileUpload component used for file uploads.
    /// </summary>
    private MudFileUpload<IBrowserFile> _fileUpload;
    private IBrowserFile _file = new DummyBrowserFile("test1.jpg", DateTimeOffset.Now, 0, "image/jpeg", []);
    private bool _uploading;
    private int _progress;
    private string _statusText = "Waiting for files.";
    /// End of MudFileUpload component
    
    protected override string Path { get; set; }

    //private MudSplitPanel _splitPanel;
    //private bool _horizontal;
    //private bool _resetOnDoubleClick = true;
    //private bool _rounded = true;
    //private bool _elevation = true;
    //private bool _transparent;

    protected override void OnInitialized()
    {
        base.OnInitialized();
        PageTitle = "Document List";
    }
    private Task OpenDialogAsync()
    {
        var options = new DialogOptions { CloseOnEscapeKey = true, MaxWidth = MaxWidth.ExtraExtraLarge, BackdropClick = false };

        return DialogService.ShowAsync<FileExplorerDialog>("File Explorer Dialog", options);
    }

    private async Task TriggerUpload()
    {
        //_fileUpload.Files?.OpenReadStream();
        using var stream = _file.OpenReadStream(5242880); // Limit to 5MB.
        using var memoryStream = new MemoryStream();
        await stream.CopyToAsync(memoryStream);
        var fileBytes = memoryStream.ToArray();

        if (stream != null)
        {
            FolderModel folderModel = new FolderModel(Guid.NewGuid(), "Trash", Guid.NewGuid());
            await DocumentsStorageService.UploadFile(stream, _file.Name, folderModel, new CancellationToken());
        }
    }
}
