<Project Sdk="Microsoft.NET.Sdk">

  <!--<PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>-->

  <PropertyGroup>
    <RootNamespace>FSH.Starter.WebApi.Keyword.Infrastructure</RootNamespace>
    <AssemblyName>FSH.Starter.WebApi.Keyword.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\framework\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Keyword.Application\Keyword.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
