// <auto-generated/>
using FSH.Starter.BlazorShared;
using Microsoft.AspNetCore.Components;

namespace FSH.Starter.Blazor.Modules.ElsaWorkflow.Blazor.Pages.StudioPages;

public partial class WorkflowInstancesList : MobulePageBase
{
    public WorkflowInstancesList()
    {
            
    }
    protected override string Path { get; set; }
    [Parameter] 
    public string Id { get; set; }
}
