// <auto-generated/>
using FSH.Starter.BlazorShared;

namespace FSH.Starter.Blazor.Modules.ElsaWorkflow.Blazor.Pages.StudioPages;

public partial class WorkflowDefinitionsList : MobulePageBase
{
    public WorkflowDefinitionsList()
    {
    }
    protected override string Path { get; set; }
}
